INDIAN_STATES = [
    "Jammu and Kashmir",
    "Himachal Pradesh",
    "Punjab",
    "Chandigarh",
    "Uttarakhand",
    "Haryana",
    "Delhi",
    "Rajasthan",
    "Uttar Pradesh",
    "Bihar",
    "Sikkim",
    "Arunachal Pradesh",
    "Nagaland",
    "Manipur",
    "Mizoram",
    "Tripura",
    "Meghalaya",
    "Assam",
    "West Bengal",
    "Jharkhand",
    "Orissa",
    "Chattisgarh",
    "Madhya Pradesh",
    "Gujarat",
    "Daman and Diu",
    "Dadar and Nagar Haveli",
    "Maharashtra",
    "Andhra Pradesh",
    "Karnataka",
    "Goa",
    "Lakshadweep",
    "Kerala",
    "Tamil Nadu",
    "Puducherry",
    "Anadaman and Nicobar Islands",
    "Telangana",
    "Andhra Pradesh",
]

DCC_EXCLUDE_ROLES = ["DCC Manager", "DCC Executive", "DCC Cashier", "Auditor"]